### ISSUE TITLE
无法编译运行

### ISSUE THREAD

**Issue by minecraft-pig** [TISUnion/most-simple-mcd#1]
C:\Users\******\Desktop\Minecraft\Server\most-simple-mcd>go build main.go
can't load package: package main.go: cannot find module providing package main.g
o

**Comment by Sciroccogti** [comment]
这个应该是运行`run.bat`编译运行？

**Comment by minecraft-pig** [comment]
这是报错

**Comment by minecraft-pig** [comment]
> 这个应该是运行`run.bat`编译运行？
这是报错
F:\Minecraft\Server\most-simple-mcd>C:\Users\GSCSDSUN\Des
ktop\Minecraft\Server\most-simple-mcd\run.bat

F:\Minecraft\Server\most-simple-mcd>go build pack-webfile
/compress-file.go

F:\Minecraft\Server\most-simple-mcd>compress-file

F:\Minecraft\Server\most-simple-mcd>go build main.go
can't load package: package main.go: cannot find module providing package main.g
o

F:\Minecraft\Server\most-simple-mcd>main
'main' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

C:\Users\GSCSDSUN\Desktop\Minecraft\Server\most-simple-mcd>

**Comment by minecraft-pig** [comment]
> 这个应该是运行`run.bat`编译运行？

找不到主类

**Comment by Sciroccogti** [comment]
目测是因为项目还在测试阶段，`main.go`文件被禁止上传了：
https://github.com/TISUnion/most-simple-mcd/blob/74a69d63fcfb1a5d4fb1628cb49d720799e299e3/.gitignore#L17

抱歉，一开始误解了您的意思。。

**Comment by minecraft-pig** [comment]
> 目测是因为项目还在测试阶段，`main.go`文件被禁止上传了：
> https://github.com/TISUnion/most-simple-mcd/blob/74a69d63fcfb1a5d4fb1628cb49d720799e299e3/.gitignore#L17
> 
> 抱歉，一开始误解了您的意思。。

好的，谢谢

**Comment by lightbrotherV** [comment]
> > 目测是因为项目还在测试阶段，`main.go`文件被禁止上传了：
> > https://github.com/TISUnion/most-simple-mcd/blob/74a69d63fcfb1a5d4fb1628cb49d720799e299e3/.gitignore#L17
> > 
> > 抱歉，一开始误解了您的意思。。
> 
> 好的，谢谢

还在开发阶段，模块化开发， 每个模块都能调，但是没集成，所以没有main.go
