### ISSUE TITLE
MCDReforged的插件是不是也支持

### ISSUE THREAD

**Issue by Worldy-MCX** [TISUnion/most-simple-mcd#4]
如果支持，使用MCDReforged的插件，是不是同样的用法

**Comment by Sciroccogti** [comment]
目前不支持，后期可能会实现MCDR的相关接口。

不过跨语言调用无论是性能还是稳定性都不是很好，所以常用插件还是尽量以重写为主。

（来自交流群内OB）

**Comment by lightbrotherV** [comment]
从技术层面上，是可以完成复用mcdr上的插件代码的，不过现在在忙别的，这个会尽快提上日程。
