### ISSUE TITLE
ubuntu 20.04以及16.04下开服失败

### ISSUE THREAD

**Issue by lawye** [TISUnion/most-simple-mcd#5]
ubuntu 16.04: 系统同时安装有apache2, 运行MCD-linux后, 在远程无法连接管理面板, 只能连接apache2. 修改mcd的端口以后依然无法连接, 关闭apache2后依旧无法连接(ping localhost可以ping通, 但是远程连接超时)
ubuntu 20.04: 系统同时安装有apache2, 同上,在apache2运行时无法连接SMCD, 关闭apache2后以超级用户运行可以连接. 启动界面提示的连接端口与设置不一致. 连接进入管理面板后, 使用1.15.2的服务端尝试开服, 修改服务端端口, 在启动以后会自动变成0, 尝试修改设置里的自动配置端口以后服务端无法启动, log显示是由于服务端端口被占用而无法连接, 然而我测试过许多端口都不能运行.

**Comment by Sciroccogti** [comment]
是云服务器还是普通电脑呢？

**Comment by lightbrotherV** [comment]
linux和mac下运行
首先确保mcd可执行文件有该目录下的所有权限（包括读写和运行）
smcd默认的web端口是80，使用 lsof -i:端口号  查看端口号是否被占用，如果被占用，视自己的情况决定要不要杀死占用80端口的进程，杀死后，重启smcd就行。

修改web端口后，连接地址会变成  < ip >:< 端口号 >   因为url不带端口号，默认是使用80端口。修改后则需要指定端口号。

**Comment by lawye** [comment]
试验环境为客户机以及阿里云ECS服务器.
已经给mcd目录777权限, 不再超级用户下启动后查看端口占用情况, 80以及233(我修改的端口)均无占用, 即MCD的管理面板没有启动成功. 
另: 我之前说的端口变成0, 是指mc的服务端的端口而不是管理面板的端口. 这个导致mc服务端无法运行.
有什么日志可以上传吗?

**Comment by lightbrotherV** [comment]
日志在mcd文件夹的logs里，请提供下gin-server里对应的日志以及default里对应的日志

**Comment by Sciroccogti** [comment]
`0~1023`为系统预留端口，请将端口号修改为大于1023且未被占用的数字再尝试一下。

另外，阿里云有安全组限制，大部分端口默认不向公网开放，也请检查一下安全组设置。

**Comment by lawye** [comment]
日志:https://github.com/lawye/ImageHubForLawye/tree/master/log

**Comment by lightbrotherV** [comment]
根据default里的日志显示是web端口和mc的端口都被占用了。 所以端口号显示为0，mc默认端口号是25565

**Comment by lawye** [comment]
MC的话, 查看日志可以看到mc以端口0启动
[Server thread/INFO]: Starting Minecraft server on *:0
完整日志在上面那个res里

**Comment by lawye** [comment]
> `0~1023`为系统预留端口，请将端口号修改为大于1023且未被占用的数字再尝试一下。
> 
> 另外，阿里云有安全组限制，大部分端口默认不向公网开放，也请检查一下安全组设置。

检查过了, 换了好几个端口都不能解决问题. 而且本地测试并没有成功, 暂时不会移植到服务器上

**Comment by lightbrotherV** [comment]
> MC的话, 查看日志可以看到mc以端口0启动
> [Server thread/INFO]: Starting Minecraft server on *:0
> 完整日志在上面那个res里

这个应该是自动更换端口的锅，win和mac还有linux的端口检测机制都不一样，得都适配下，如果是0，直接在后台更换端口应该就能规避。

**Comment by lawye** [comment]
> > MC的话, 查看日志可以看到mc以端口0启动
> > [Server thread/INFO]: Starting Minecraft server on *:0
> > 完整日志在上面那个res里
> 
> 这个应该是自动更换端口的锅，win和mac还有linux的端口检测机制都不一样，得都适配下，如果是0，直接在后台更换端口应该就能规避。

我一开始把自动更换端口功能关闭，启动不了服务器，原因是端口被占用，所以没有开始启动。然后打开功能，直接修改server.propertity里面的端口，启动后又被修改为0。

**Comment by lightbrotherV** [comment]
> > > MC的话, 查看日志可以看到mc以端口0启动
> > > [Server thread/INFO]: Starting Minecraft server on *:0
> > > 完整日志在上面那个res里
> > 
> > 
> > 这个应该是自动更换端口的锅，win和mac还有linux的端口检测机制都不一样，得都适配下，如果是0，直接在后台更换端口应该就能规避。
> 
> 我一开始把自动更换端口功能关闭，启动不了服务器，原因是端口被占用，所以没有开始启动。然后打开功能，直接修改server.propertity里面的端口，启动后又被修改为0。

要在web后台里修改，在server.propertity里修改时没有用的。

**Comment by lawye** [comment]
> > > > MC的话, 查看日志可以看到mc以端口0启动
> > > > [Server thread/INFO]: Starting Minecraft server on *:0
> > > > 完整日志在上面那个res里
> > > 
> > > 
> > > 这个应该是自动更换端口的锅，win和mac还有linux的端口检测机制都不一样，得都适配下，如果是0，直接在后台更换端口应该就能规避。
> > 
> > 
> > 我一开始把自动更换端口功能关闭，启动不了服务器，原因是端口被占用，所以没有开始启动。然后打开功能，直接修改server.propertity里面的端口，启动后又被修改为0。
> 
> 要在web后台里修改，在server.propertity里修改时没有用的。

如果说web后台是指在添加服务端那个界面修改对应服务端启动参数之类的话，我尝试过了。修改为其他的数，启动后自动变成0

**Comment by lightbrotherV** [comment]
修改后端口也是没有被占用的吗？尝试下把自动更换端口禁用，然后修改

**Comment by lawye** [comment]
> 修改后端口也是没有被占用的吗？尝试下把自动更换端口禁用，然后修改

端口无占用。禁用以后似乎由于smcd的端口检测问题，在日志里会报一个端口被占用的错，然后mc就中止启动。查看mc的日志可以发现没有启动（mclog里面没有对应日志）

**Comment by lightbrotherV** [comment]
懂了，端口检测在linux中出现了问题，感谢提供宝贵意见。

**Comment by lightbrotherV** [comment]
bug已修复
